from dataclasses import dataclass, field
from typing import Dict, List, Tuple


@dataclass
class FrameworkProfile:
    name: str
    language: str
    database: str
    include_dirs: List[str]
    include_files: List[str]
    extra_exclude_dirs: List[str]
    section_map: Dict[str, str]
    parts: List[Tuple[str, str]]
    detect_files: List[str]
    stat_labels: Dict[str, str]


LARAVEL = FrameworkProfile(
    name="Laravel",
    language="PHP",
    database="MySQL",
    include_dirs=[
        "app",
        "config",
        "database/migrations",
        "database/seeders",
        "database/factories",
        "resources/views",
        "resources/css",
        "resources/js",
        "routes",
        "tests",
        "public/css",
        "public/javascript",
        "bootstrap",
    ],
    include_files=[
        "artisan",
        "composer.json",
        "composer.lock",
        "package.json",
        "package-lock.json",
        "vite.config.js",
        "tailwind.config.js",
        "postcss.config.js",
        "README.md",
        "SECURITY_AUDIT.md",
        ".env.example",
        "public/index.php",
        "public/sw.js",
        "public/manifest.json",
        "public/offline.html",
        "bootstrap/app.php",
        "bootstrap/providers.php",
    ],
    extra_exclude_dirs=["bootstrap/cache", "public/build"],
    section_map={
        "Http/Controllers": "Controllers",
        "Models": "Models",
        "Http/Middleware": "Middleware",
        "Http/Requests": "Requests",
        "Services": "Services",
        "Notifications": "Notifications",
        "Traits": "Traits",
        "Jobs": "Jobs",
        "Observers": "Observers",
        "Listeners": "Listeners",
        "Helpers": "Helpers",
        "Console/Commands": "Commands",
        "Providers": "Providers",
        "Exceptions": "Exceptions",
        "Policies": "Policies",
        "Casts": "Casts",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Application Source Code"),
        ("III", "Configuration"),
        ("IV", "Database"),
        ("V", "Routes"),
        ("VI", "Views"),
        ("VII", "Frontend Assets"),
        ("VIII", "Bootstrap"),
        ("IX", "Tests"),
    ],
    detect_files=["artisan", "bootstrap/app.php"],
    stat_labels={
        "Controllers": "Controllers",
        "Models": "Models",
        "Services": "Services",
        "Middleware": "Middleware",
        "Requests": "Requests",
        "Blade Templates": "Blade Templates",
        "JavaScript": "JavaScript Files",
        "CSS": "CSS Files",
        "PHP": "PHP Files",
        "Migrations": "Migrations",
        "Seeders": "Seeders",
        "Factories": "Factories",
        "Config": "Config Files",
        "Tests": "Tests",
    },
)

FLASK = FrameworkProfile(
    name="Flask",
    language="Python",
    database="SQLite/PostgreSQL",
    include_dirs=[
        "app",
        "templates",
        "static/css",
        "static/js",
        "tests",
        "migrations",
    ],
    include_files=[
        "run.py",
        "app.py",
        "requirements.txt",
        "config.py",
        ".env.example",
        "README.md",
        "wsgi.py",
        "Pipfile",
        "setup.py",
    ],
    extra_exclude_dirs=["__pycache__", ".venv", "venv", "instance"],
    section_map={
        "routes": "Routes",
        "models": "Models",
        "templates": "Templates",
        "services": "Services",
        "utils": "Utilities",
        "static/css": "CSS",
        "static/js": "JavaScript",
        "tests": "Tests",
        "migrations": "Migrations",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Application Source Code"),
        ("III", "Configuration"),
        ("IV", "Templates"),
        ("V", "Static Assets"),
        ("VI", "Database & Migrations"),
        ("VII", "Tests"),
    ],
    detect_files=["requirements.txt", "run.py", "app.py"],
    stat_labels={
        "Routes": "Routes",
        "Models": "Models",
        "Templates": "Templates",
        "Services": "Services",
        "Utilities": "Utilities",
        "Python": "Python Files",
        "JavaScript": "JavaScript Files",
        "CSS": "CSS Files",
        "HTML": "HTML Templates",
        "Tests": "Tests",
        "Migrations": "Migrations",
    },
)

VANILLA_PHP = FrameworkProfile(
    name="Vanilla PHP",
    language="PHP",
    database="MySQL",
    include_dirs=[
        "public",
        "includes",
        "classes",
        "templates",
        "sql",
        "tests",
        "config",
        "src",
        "lib",
        "assets/css",
        "assets/js",
    ],
    include_files=[
        "index.php",
        ".htaccess",
        "composer.json",
        "composer.lock",
        "README.md",
        ".env.example",
        "config.php",
    ],
    extra_exclude_dirs=["vendor", "node_modules"],
    section_map={
        "classes": "Classes",
        "includes": "Includes",
        "templates": "Templates",
        "sql": "SQL",
        "src": "Source",
        "lib": "Library",
        "config": "Configuration",
        "tests": "Tests",
        "assets/css": "CSS",
        "assets/js": "JavaScript",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Source Code"),
        ("III", "Configuration"),
        ("IV", "Templates"),
        ("V", "Assets"),
        ("VI", "Database & SQL"),
        ("VII", "Tests"),
    ],
    detect_files=["index.php"],
    stat_labels={
        "Classes": "Classes",
        "Includes": "Includes",
        "Templates": "Templates",
        "PHP": "PHP Files",
        "CSS": "CSS Files",
        "JavaScript": "JavaScript Files",
        "SQL": "SQL Files",
        "Tests": "Tests",
    },
)

DJANGO = FrameworkProfile(
    name="Django",
    language="Python",
    database="PostgreSQL/SQLite",
    include_dirs=[
        "templates",
        "static",
        "management/commands",
        "migrations",
        "tests",
        "templatetags",
        "staticfiles",
    ],
    include_files=[
        "manage.py",
        "requirements.txt",
        "settings.py",
        "urls.py",
        "wsgi.py",
        "asgi.py",
        ".env.example",
        "README.md",
        "Pipfile",
    ],
    extra_exclude_dirs=["__pycache__", ".venv", "venv", "staticfiles", "media"],
    section_map={
        "views": "Views",
        "models": "Models",
        "serializers": "Serializers",
        "admin": "Admin",
        "forms": "Forms",
        "urls": "URL Configuration",
        "templates": "Templates",
        "management/commands": "Management Commands",
        "templatetags": "Template Tags",
        "tests": "Tests",
        "migrations": "Migrations",
        "signals": "Signals",
        "middleware": "Middleware",
        "permissions": "Permissions",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Application Source Code"),
        ("III", "Settings & Configuration"),
        ("IV", "Templates"),
        ("V", "Static Assets"),
        ("VI", "Database & Migrations"),
        ("VII", "Tests"),
    ],
    detect_files=["manage.py"],
    stat_labels={
        "Views": "Views",
        "Models": "Models",
        "Serializers": "Serializers",
        "Forms": "Forms",
        "Admin": "Admin",
        "Templates": "Templates",
        "Python": "Python Files",
        "HTML": "HTML Templates",
        "CSS": "CSS Files",
        "JavaScript": "JavaScript Files",
        "Tests": "Tests",
        "Migrations": "Migrations",
    },
)

EXPRESS = FrameworkProfile(
    name="Express/Node.js",
    language="JavaScript/TypeScript",
    database="MongoDB/PostgreSQL",
    include_dirs=[
        "src",
        "routes",
        "controllers",
        "models",
        "middleware",
        "views",
        "config",
        "public/css",
        "public/js",
        "tests",
        "test",
    ],
    include_files=[
        "package.json",
        "package-lock.json",
        "server.js",
        "app.js",
        "index.js",
        ".env.example",
        "README.md",
        "tsconfig.json",
        ".eslintrc.js",
    ],
    extra_exclude_dirs=["node_modules", ".next", "dist", "build"],
    section_map={
        "routes": "Routes",
        "controllers": "Controllers",
        "models": "Models",
        "middleware": "Middleware",
        "views": "Views",
        "config": "Configuration",
        "src/routes": "Routes",
        "src/controllers": "Controllers",
        "src/models": "Models",
        "src/middleware": "Middleware",
        "src/services": "Services",
        "src/utils": "Utilities",
        "tests": "Tests",
        "test": "Tests",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Application Source Code"),
        ("III", "Configuration"),
        ("IV", "Views & Templates"),
        ("V", "Public Assets"),
        ("VI", "Tests"),
    ],
    detect_files=["package.json", "server.js", "app.js", "index.js"],
    stat_labels={
        "Routes": "Routes",
        "Controllers": "Controllers",
        "Models": "Models",
        "Middleware": "Middleware",
        "Services": "Services",
        "Utilities": "Utilities",
        "JavaScript": "JavaScript Files",
        "TypeScript": "TypeScript Files",
        "CSS": "CSS Files",
        "HTML": "HTML Templates",
        "Tests": "Tests",
    },
)

REACT = FrameworkProfile(
    name="React",
    language="JavaScript/TypeScript",
    database="N/A (Frontend)",
    include_dirs=[
        "src/components",
        "src/pages",
        "src/views",
        "src/services",
        "src/utils",
        "src/store",
        "src/hooks",
        "src/context",
        "src/types",
        "public",
    ],
    include_files=[
        "package.json",
        "package-lock.json",
        "vite.config.js",
        "tsconfig.json",
        ".env.example",
        "README.md",
        "index.html",
        "next.config.js",
    ],
    extra_exclude_dirs=["node_modules", "build", "dist", ".next"],
    section_map={
        "components": "Components",
        "pages": "Pages",
        "views": "Views",
        "services": "Services",
        "utils": "Utilities",
        "store": "State Management",
        "hooks": "Hooks",
        "context": "Context",
        "types": "Type Definitions",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Components & Pages"),
        ("III", "Services & Utilities"),
        ("IV", "State Management"),
        ("V", "Public Assets"),
        ("VI", "Configuration"),
    ],
    detect_files=["package.json"],
    stat_labels={
        "Components": "Components",
        "Pages": "Pages",
        "Hooks": "Hooks",
        "Services": "Services",
        "Utilities": "Utilities",
        "JavaScript": "JavaScript Files",
        "TypeScript": "TypeScript Files",
        "CSS": "CSS Files",
        "HTML": "HTML Templates",
    },
)

VUE = FrameworkProfile(
    name="Vue",
    language="JavaScript/TypeScript",
    database="N/A (Frontend)",
    include_dirs=[
        "src/components",
        "src/views",
        "src/pages",
        "src/services",
        "src/utils",
        "src/store",
        "src/composables",
        "src/types",
        "public",
    ],
    include_files=[
        "package.json",
        "package-lock.json",
        "vite.config.js",
        "tsconfig.json",
        ".env.example",
        "README.md",
        "index.html",
        "vue.config.js",
        "nuxt.config.js",
    ],
    extra_exclude_dirs=["node_modules", "build", "dist", ".nuxt"],
    section_map={
        "components": "Components",
        "views": "Views",
        "pages": "Pages",
        "services": "Services",
        "utils": "Utilities",
        "store": "State Management",
        "composables": "Composables",
        "types": "Type Definitions",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Components & Views"),
        ("III", "Services & Utilities"),
        ("IV", "State Management"),
        ("V", "Public Assets"),
        ("VI", "Configuration"),
    ],
    detect_files=["package.json"],
    stat_labels={
        "Components": "Components",
        "Views": "Views",
        "Composables": "Composables",
        "Services": "Services",
        "Utilities": "Utilities",
        "JavaScript": "JavaScript Files",
        "TypeScript": "TypeScript Files",
        "CSS": "CSS Files",
        "HTML": "HTML Templates",
    },
)

ANGULAR = FrameworkProfile(
    name="Angular",
    language="TypeScript",
    database="N/A (Frontend)",
    include_dirs=[
        "src/app",
        "src/assets",
        "src/environments",
        "e2e",
    ],
    include_files=[
        "package.json",
        "package-lock.json",
        "angular.json",
        "tsconfig.json",
        "tsconfig.app.json",
        ".env.example",
        "README.md",
        "src/index.html",
    ],
    extra_exclude_dirs=["node_modules", "dist", ".angular"],
    section_map={
        "components": "Components",
        "services": "Services",
        "pipes": "Pipes",
        "directives": "Directives",
        "guards": "Guards",
        "interceptors": "Interceptors",
        "modules": "Modules",
        "models": "Models",
        "environments": "Environments",
    },
    parts=[
        ("I", "Root Files"),
        ("II", "Components"),
        ("III", "Services & Utilities"),
        ("IV", "Assets"),
        ("V", "Configuration"),
        ("VI", "Tests"),
    ],
    detect_files=["angular.json"],
    stat_labels={
        "Components": "Components",
        "Services": "Services",
        "Pipes": "Pipes",
        "Directives": "Directives",
        "Guards": "Guards",
        "Modules": "Modules",
        "TypeScript": "TypeScript Files",
        "HTML": "HTML Templates",
        "CSS": "CSS Files",
        "Tests": "Tests",
    },
)

ALL_PROFILES: Dict[str, FrameworkProfile] = {
    "Laravel": LARAVEL,
    "Flask": FLASK,
    "Vanilla PHP": VANILLA_PHP,
    "Django": DJANGO,
    "Express/Node.js": EXPRESS,
    "React": REACT,
    "Vue": VUE,
    "Angular": ANGULAR,
}


def get_profile(name: str) -> FrameworkProfile:
    if name in ALL_PROFILES:
        return ALL_PROFILES[name]
    raise ValueError(f"Unknown framework: {name}. Available: {', '.join(ALL_PROFILES.keys())}")
